# Generated by Django 6.0.1 on 2026-01-14 09:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Tavsif kiritilmagan')),
                ('category', models.CharField(choices=[('network', 'Tarmoq'), ('linux', 'Linux'), ('security', 'Xavfsizlik'), ('cloud', 'Cloud'), ('devops', 'DevOps')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('lessons_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('order', models.PositiveIntegerField()),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('slide', models.FileField(blank=True, null=True, upload_to='courses/slides/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='kurs.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
