# Generated by Django 6.0.1 on 2026-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0004_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', upload_to='course_images/', verbose_name='Kurs rasmi'),
        ),
    ]
