# Generated by Django 6.0.1 on 2026-01-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0005_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
