# Generated by Django 6.0.1 on 2026-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0007_remove_lesson_video_url_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Kurs Rasmi'),
        ),
    ]
