# Generated by Django 6.0.1 on 2026-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0008_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Dars ochiqmi?'),
        ),
    ]
